version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/https/:/https/
    extra_hosts:
    - "host.docker.internal:host-gateway"
    restart: unless-stopped